# Generated by Django 5.0.3 on 2024-11-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
